version: "2"
volumes:
  execute0pr.sipher.cerberus.net: null
networks:
  cerberusntw: null
services:
  couchdb.execute0pr.sipher:
    container_name: couchdb.execute0pr.sipher
    image: hyperledger/fabric-couchdb:$IMAGE_TAG
    environment:
    - COUCHDB_USER=userexecute0prsipher
    - COUCHDB_PASSWORD=passwordexecute0prsipher
    ports:
    - 10020:5984
    networks:
    - cerberusntw
  execute0pr.sipher.cerberus.net:
    extends:
      file: ../base/docker-compose-sipher-base.yaml
      service: execute0pr.sipher.cerberus.net
    environment:
    - CORE_PEER_ID=execute0pr.sipher.cerberus.net
    - CORE_PEER_ADDRESS=execute0pr.sipher.cerberus.net
    - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
    - CORE_PEER_CHAINCODEADDRESS=execute0pr.sipher.cerberus.net:10018
    - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10018
    - CORE_PEER_GOSSIP_USELEADERELECTION=false
    - CORE_PEER_GOSSIP_BOOTSTRAP=lead0pr.sipher.cerberus.net:7051
    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=anchorpr.sipher.cerberus.net:7051
    - CORE_PEER_LOCALMSPID=SipherMSP
    - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
    - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.execute0pr.sipher:5984
    - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=userexecute0prsipher
    - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=passwordexecute0prsipher
    volumes:
    - /var/run/:/host/var/run/
    - ../crypto-config/peerOrganizations/sipher.cerberus.net/peers/execute0pr.sipher.cerberus.net/msp:/etc/hyperledger/fabric/msp
    - ../crypto-config/peerOrganizations/sipher.cerberus.net/peers/execute0pr.sipher.cerberus.net/tls:/etc/hyperledger/fabric/tls
    - execute0pr.sipher.cerberus.net:/var/hyperledger/production
    ports:
    - 10017:7051
    - 10018:7052
    - 10019:7053
    networks:
    - cerberusntw
    depends_on:
    - couchdb.execute0pr.sipher
  cli.execute0pr.sipher.cerberus.net:
    container_name: cli.execute0pr.sipher.cerberus.net
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
    - GOPATH=/opt/gopath
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - FABRIC_LOGGING_SPEC=INFO
    - CORE_PEER_ID=cli.execute0pr.sipher.cerberus.net
    - CORE_PEER_ADDRESS=execute0pr.sipher.cerberus.net:7051
    - CORE_PEER_LOCALMSPID=SipherMSP
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sipher.cerberus.net/peers/execute0pr.sipher.cerberus.net/tls/server.crt
    - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sipher.cerberus.net/peers/execute0pr.sipher.cerberus.net/tls/server.key
    - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sipher.cerberus.net/users/Admin@sipher.cerberus.net/msp
    - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sipher.cerberus.net/users/Admin@sipher.cerberus.net/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
    - /var/run/:/host/var/run/
    - ../../../chaincode/:/opt/gopath/src/github.com/chaincode
    - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
    - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
    - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
    - execute0pr.sipher.cerberus.net
    networks:
    - cerberusntw

~    
